"""Create initial tables

Revision ID: 304f2c8bb6c8
Revises:        # noqa W291
Create Date: 2022-01-24 01:21:23.718610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "304f2c8bb6c8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("label", sa.VARCHAR(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_index(op.f("ix_images_label"), "images", ["label"], unique=False)
    op.create_table(
        "detected_objects",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("image_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detected_objects_id"), "detected_objects", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_detected_objects_image_id"),
        "detected_objects",
        ["image_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detected_objects_name"), "detected_objects", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detected_objects_name"), table_name="detected_objects")
    op.drop_index(op.f("ix_detected_objects_image_id"), table_name="detected_objects")
    op.drop_index(op.f("ix_detected_objects_id"), table_name="detected_objects")
    op.drop_table("detected_objects")
    op.drop_index(op.f("ix_images_label"), table_name="images")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
